export const ADD_WORD_REQUEST = "ADD_WORD_REQUEST";
export const ADD_WORD_SUCCESS = "ADD_WORD_SUCCESS";
export const ADD_WORD_ERROR = "ADD_WORD_ERROR";

export const FETCH_WORDS_SUCCESS = "FETCH_WORDS_SUCCESS";
export const FETCH_WORDS_REQUEST = "FETCH_WORDS_REQUEST";
export const FETCH_WORDS_ERROR = "FETCH_WORDS_ERROR";
